name: test01
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_ui_firestore: ^1.5.13
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  mime: ^1.0.4
  modal_progress_hud_nsn: ^0.4.0
  table_calendar: ^3.0.9
  animations: ^2.0.8
  adaptive_components: ^0.0.9
  image_cropper: ^5.0.1
  path_provider: ^2.1.1
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SOYO
      fonts:
      - asset: assets/fonts/SOYO Maple Regular.ttf
      - asset: assets/fonts/SOYO Maple Bold.ttf