// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhQKhcv4sAdOP9hxcj1_9NMRhb3ORrek',
    appId: '1:832909857631:web:d3d111c96b2e93cba99cea',
    messagingSenderId: '832909857631',
    projectId: 'coffeereadingbook',
    authDomain: 'coffeereadingbook.firebaseapp.com',
    storageBucket: 'coffeereadingbook.appspot.com',
    measurementId: 'G-MTM4B84T9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEgCHEAcVLPzzbaDSxSCZ64-CGH-FbbA',
    appId: '1:832909857631:android:08db18c0f10cced1a99cea',
    messagingSenderId: '832909857631',
    projectId: 'coffeereadingbook',
    storageBucket: 'coffeereadingbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFsem3nIxUhdBOaeUg6QpbLOmEZ6_4u0',
    appId: '1:832909857631:ios:b2209886dab621c4a99cea',
    messagingSenderId: '832909857631',
    projectId: 'coffeereadingbook',
    storageBucket: 'coffeereadingbook.appspot.com',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkFsem3nIxUhdBOaeUg6QpbLOmEZ6_4u0',
    appId: '1:832909857631:ios:1c37b5387aceaa11a99cea',
    messagingSenderId: '832909857631',
    projectId: 'coffeereadingbook',
    storageBucket: 'coffeereadingbook.appspot.com',
    iosBundleId: 'com.example.test01.RunnerTests',
  );
}
